FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

ARG JAR_FILE
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["sh", "-c"]
CMD ["java $JAVA_OPTS -jar app.jar"]
