rootProject.name = 'dobonglife'
include 'core'
include 'domain-user'
include 'application'
include 'domain-place'
include 'domain-course'
include 'domain-schedule'
include 'domain-promotion'
include 'domain-coupon'
include 'domain-business'
include 'domain-notification'
include 'domain-point'
include 'domain-like'
include 'domain-review'
include 'infra'
include 'api'
