spring:
  application:
    name: dobonglife
  profiles:
    group:
      local: local-db, common
      prod: prod-db, common
    active: local

  config:
    activate:
      on-profile: common
    import: optional:file:.env[.properties]

  web:
    resources:
      add-mappings: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs/swagger
    urls:
      - name: Springdoc
        url: /v3/api-docs
      - name: RestDocs
        url: /docs/openapi3.json
    urls-primary-name: Springdoc
jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRED_IN}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRED_IN}
    header: Authorization-refresh

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
