server:
  port: 8082

spring:
  application:
    name: domain-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/dobonglife_commerce?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
