server:
  port: 8084

spring:
  application:
    name: domain-auth
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: ${AUTH_DATASOURCE_URL:${LOCAL_DATASOURCE_URL:${DB_URL:jdbc:mysql://localhost:3306/dobonglife_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}}}
    username: ${AUTH_DATASOURCE_USERNAME:${LOCAL_DATASOURCE_USERNAME:${DB_USERNAME:root}}}
    password: ${AUTH_DATASOURCE_PASSWORD:${LOCAL_DATASOURCE_PASSWORD:${DB_PASSWORD:}}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        allowPublicKeyRetrieval: true
        useSSL: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            client-name: kakao
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI:}
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET_KEY:}
  access:
    expiration: ${JWT_ACCESS_EXPIRED_IN:0}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRED_IN:0}

kakao:
  admin-key: ${KAKAO_ADMIN_KEY:}

apple:
  client-id: ${APPLE_CLIENT_ID:}
  team-id: ${APPLE_TEAM_ID:}
  key-id: ${APPLE_KEY_ID:}
  private-key-path: ${APPLE_PRIVATE_KEY_PATH:}
